### PR TITLE
Updates to Language

### PR DESCRIPTION
**Pull request by Vachenzo**
I forgot how huge this task is.

Along with these edits, I wanted to share a book with you. It's called "The Disappearing Spoon" and goes into the history of the Periodic Table and each of the elements contained within it: http://samkean.com/disappearing-spoon I thought maybe you'd enjoy it if you wrote a whole mission on the Periodic Table.

### CODE REVIEW

**Comment by suwanditan** [comment]
Wow, what a resource! Thanks, Ryan. I'll try to hunt it down this weekend :)
I read the book review and, the review is good. 

Yes, I love this subject, and of course, I wrote this specificly for CheckiO task!
I got this subject back because months ago, a subscription channel, broadcasted a documentary, named "Elements".
This is like "Disappearing Spoon" story, but in tv format. It shook me awhile that the element (which I memorized with silly mnemonics for remembering the sequence)
, each had a unique story of its discovery. That's why I shared the wonders :)

Anyway, here is my reference when created Periodic Table task:
1. Fundamentals of College Physics, Peter J. Nolan
2. RSC ( Royal Society of Chemistry ) Visual Elements and Periodic Table History, www.rsc.org
3. The Elements Series, by Professor Jim Al-Khalili - BBC Knowledge Channel
4. Wikipedia

**Comment by Vachenzo** [comment]
I hope you enjoy it! It's a cool book and gives you loads of history on
each element.

**Comment by suwanditan** [comment]
Ho..ho..ho.. I will ! thanks for sharing :)

**Comment by suwanditan** [comment]
Anyway, Ryan, I keep the words "in ground state", because elements has another form, which is, ions. When this occurs, number of protons and electrons would not be in same amount. However, I parenthesized this.

**Comment by Vachenzo** [comment]
Good to know. I wasn't sure about that bit anyway. Thanks for the update.

**Pull request merged**
